# source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
platform :osx, '10.13'

target 'IMPFileManager-Pod' do
    inherit! :search_paths
    
    #
    # develop ode
    #
    pod 'IMPFileManager', :path => '../../'
    
end

target 'IMPFileManager-PodTests' do
  inherit! :search_paths
end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
    end
  end
end
